#!/usr/bin/env bash
# generate-backend-report.sh — Minimal bulletproof version
set +e  # NEVER exit on error

ARCH="${ARCH:-unknown}"
cd "${GITHUB_WORKSPACE:-.}" 2>/dev/null || true

COMMIT_SHORT="unknown"
if [ -n "${COMMIT_SHA:-}" ]; then
  COMMIT_SHORT="${COMMIT_SHA:0:7}"
fi

BRANCH="${BRANCH:-develop}"
RUN_DATE="${RUN_DATE:-unknown}"
RUN_URL="${RUN_URL:-#}"
RUSTC_VER="${RUSTC_VER:-unknown}"
BUILD_STATUS="${BUILD_STATUS:-unknown}"
BIN_SIZE="${BIN_SIZE:-N/A}"
CHECK_EXIT="${CHECK_EXIT:-?}"
CLIPPY_EXIT="${CLIPPY_EXIT:-?}"
BUILD_DURATION="${BUILD_DURATION:-N/A}"
WARNINGS_COUNT="${WARNINGS_COUNT:-N/A}"
ERRORS_COUNT="${ERRORS_COUNT:-N/A}"
NEW_WARNINGS="${NEW_WARNINGS:-N/A}"

[ "$BUILD_STATUS" = "OK" ] && BUILD_ICON="✅" || BUILD_ICON="❌"

REPORT=".claude/BACKEND-BUILD-REPORT-${ARCH}.md"
mkdir -p .claude 2>/dev/null || mkdir -p .claude

cat > "$REPORT" << ENDREPORT
# Backend Build Report — ${ARCH} — Nook

**${RUN_DATE}**

| Field | Value |
|-------|-------|
| Architecture | ${ARCH} |
| Branch | ${BRANCH} |
| Commit | ${COMMIT_SHORT} |
| Rust | ${RUSTC_VER} |
| Build | ${BUILD_ICON} ${BUILD_STATUS} |
| cargo check | exit=${CHECK_EXIT} |
| cargo clippy | exit=${CLIPPY_EXIT} |
| Binary | ${BIN_SIZE} |
| Duration | ${BUILD_DURATION} |
| Warnings | ${WARNINGS_COUNT} |
| Errors | ${ERRORS_COUNT} |
| New | ${NEW_WARNINGS} |
| Run | ${RUN_URL} |

*Generated by .github/scripts/generate-backend-report.sh*
ENDREPORT

echo "Backend report generated"
exit 0
