#!/usr/bin/env bash
# generate-frontend-report.sh
# Env vars: RUN_DATE, COMMIT_SHA, BRANCH, RUN_URL, BUILD_STATUS, NODE_VER,
#   BUILD_DURATION, OUTPUT_SIZE, FILE_COUNT
set +e
cd "${GITHUB_WORKSPACE:-.}" 2>/dev/null || true

COMMIT_SHA="${COMMIT_SHA:-unknown}"
COMMIT_SHORT="${COMMIT_SHA:0:7}"
BRANCH="${BRANCH:-develop}"
RUN_DATE="${RUN_DATE:-unknown}"
RUN_URL="${RUN_URL:-#}"
BUILD_STATUS="${BUILD_STATUS:-unknown}"
NODE_VER="${NODE_VER:-unknown}"
BUILD_DURATION="${BUILD_DURATION:-N/A}"
OUTPUT_SIZE="${OUTPUT_SIZE:-N/A}"
FILE_COUNT="${FILE_COUNT:-N/A}"

[ "$BUILD_STATUS" = "OK" ] && STATUS_ICON="✅" || STATUS_ICON="❌"

VITE_MS="N/A"
[ -f /tmp/frontend-build.txt ] && VITE_MS=$(grep -oP 'built in \K[0-9.]+' /tmp/frontend-build.txt 2>/dev/null | head -1) || true
[ -z "$VITE_MS" ] && VITE_MS="N/A"

WARN_COUNT="N/A"
ERR_COUNT="N/A"
CHUNK_COUNT="N/A"
if [ -f /tmp/frontend-build.txt ]; then
  WARN_COUNT=$(grep -cE "WARNING|warning" /tmp/frontend-build.txt 2>/dev/null) || true
  ERR_COUNT=$(grep -cE "^Error|error TS" /tmp/frontend-build.txt 2>/dev/null) || true
  CHUNK_COUNT=$(grep -cE "kB|gzip" /tmp/frontend-build.txt 2>/dev/null) || true
fi

WARNINGS="(aucun)"
ERRORS="(aucune)"
VITE_SUMMARY="(non disponible)"
if [ -f /tmp/frontend-build.txt ]; then
  WARNINGS=$(grep -E "WARNING|warning" /tmp/frontend-build.txt 2>/dev/null | head -30) || true
  ERRORS=$(grep -E "^Error|error TS" /tmp/frontend-build.txt 2>/dev/null | head -30) || true
  VITE_SUMMARY=$(grep -E "modules transformed|built in" /tmp/frontend-build.txt 2>/dev/null | head -10) || true
fi

CHUNKS="(non disponible)"
[ -f /tmp/frontend-build.txt ] && CHUNKS=$(grep -E "kB|gzip" /tmp/frontend-build.txt 2>/dev/null | tail -30) || true

REPORT=".hermes/FRONTEND-BUILD-REPORT.md"
mkdir -p .hermes 2>/dev/null || true

cat > "$REPORT" << ENDOFMD
# Frontend Build Report — Nook

**${RUN_DATE}**

| Champ | Valeur |
|-------|--------|
| **Build** | ${STATUS_ICON} ${BUILD_STATUS} |
| **Branche** | ${BRANCH} |
| **Commit** | ${COMMIT_SHORT} |
| **Node.js** | ${NODE_VER} |
| **Vite time** | ${VITE_MS}ms |
| **Duration** | ${BUILD_DURATION} |
| **Output** | ${OUTPUT_SIZE} |
| **Files** | ${FILE_COUNT} |
| **Warnings** | ${WARN_COUNT} |
| **Errors** | ${ERR_COUNT} |
| **Chunks** | ${CHUNK_COUNT} |
| **Run** | ${RUN_URL} |

---

## Erreurs

\`\`\`
${ERRORS}
\`\`\`

## Warnings

\`\`\`
${WARNINGS}
\`\`\`

## Bundle

\`\`\`
${VITE_SUMMARY}

${CHUNKS}
\`\`\`

*Generated by .github/scripts/generate-frontend-report.sh*
ENDOFMD

echo "Frontend report generated"
exit 0
