#!/usr/bin/env bash
# generate-docker-report.sh
# Env vars: RUN_DATE, COMMIT_SHA, BRANCH, RUN_URL, VERSION, IMAGE,
#   PUSH_DIGEST, BUILD_DURATION, AMD64_SIZE, ARM64_SIZE, FRONT_FILES
set +e
cd "${GITHUB_WORKSPACE:-.}" 2>/dev/null || true

COMMIT_SHA="${COMMIT_SHA:-unknown}"
COMMIT_SHORT="${COMMIT_SHA:0:7}"
BRANCH="${BRANCH:-develop}"
RUN_DATE="${RUN_DATE:-unknown}"
RUN_URL="${RUN_URL:-#}"
VERSION="${VERSION:-unknown}"
IMAGE="${IMAGE:-unknown}"
PUSH_DIGEST="${PUSH_DIGEST:-N/A}"
BUILD_DURATION="${BUILD_DURATION:-N/A}"
FRONT_FILES="${FRONT_FILES:-N/A}"
AMD64_SIZE="${AMD64_SIZE:-N/A}"
ARM64_SIZE="${ARM64_SIZE:-N/A}"

[ -n "$PUSH_DIGEST" ] && PUSH_STATUS="✅ OK" || PUSH_STATUS="❌ FAIL"

AMD64_STATUS="✅"
ARM64_STATUS="✅"
[ ! -f "docker-context/backend/nook-backend-amd64" ] && AMD64_STATUS="❌ manquant"
[ ! -f "docker-context/backend/nook-backend-arm64" ] && ARM64_STATUS="❌ manquant"

BUILD_LOGS="(non capturé)"
[ -f /tmp/docker-build.txt ] && BUILD_LOGS=$(tail -30 /tmp/docker-build.txt 2>/dev/null) || true

REPORT=".hermes/DOCKER-BUILD-REPORT.md"
mkdir -p .hermes 2>/dev/null || true

cat > "$REPORT" << ENDOFMD
# Docker Build Report — Nook

**${RUN_DATE}**

| Champ | Valeur |
|-------|--------|
| **Push GHCR** | ${PUSH_STATUS} |
| **Version** | ${VERSION} |
| **Image** | ${IMAGE} |
| **Digest** | ${PUSH_DIGEST} |
| **Branche** | ${BRANCH} |
| **Commit** | ${COMMIT_SHORT} |
| **Duration** | ${BUILD_DURATION} |
| **Frontend** | ${FRONT_FILES} |
| **Run** | ${RUN_URL} |

---

## Multi-platform

| Platform | Taille | Statut |
|----------|--------|--------|
| linux/amd64 | ${AMD64_SIZE} | ${AMD64_STATUS} |
| linux/arm64 | ${ARM64_SIZE} | ${ARM64_STATUS} |

---

## Build logs

\`\`\`
${BUILD_LOGS}
\`\`\`

*Generated by .github/scripts/generate-docker-report.sh*
ENDOFMD

echo "Docker report generated"
exit 0
