# ── Turn-Server Configuration ──
# Éditer ce fichier pour personnaliser le serveur TURN/STUN
# Après modification : docker compose restart turn

[server]
name = "nook.local"
secret = "change_this_turn_secret_2026"
max-threads = 0

[[server.interfaces]]
transport = "udp"
listen = "0.0.0.0:3478"
external = "0.0.0.0:3478"

[[server.interfaces]]
transport = "tcp"
listen = "0.0.0.0:3478"
external = "0.0.0.0:3478"
